const mongoose = require('mongoose');

const scoreSchema = mongoose.Schema({
    courseName: {type: String, required: true},
    playerName: {type: String},
    hole1: {type: Number, default: 3},
    par1: {type: Number, default: 3},
    hole2: {type: Number, default: 3},
    par2: {type: Number, default: 3},
    hole3: {type: Number, default: 3},
    par3: {type: Number, default: 3},
    hole4: {type: Number, default: 3},
    par4: {type: Number, default: 3},
    hole5: {type: Number, default: 3},
    par5: {type: Number, default: 3},
    hole6: {type: Number, default: 3},
    par6: {type: Number, default: 3},
    hole7: {type: Number, default: 3},
    par7: {type: Number, default: 3},
    hole8: {type: Number, default: 3},
    par8: {type: Number, default: 3},
    hole9: {type: Number, default: 3},
    par9: {type: Number, default: 3},
    hole10: {type: Number, default: 3},
    par10: {type: Number, default: 3},
    hole11: {type: Number, default: 3},
    par11: {type: Number, default: 3},
    hole12: {type: Number, default: 3},
    par12: {type: Number, default: 3},
    hole13: {type: Number, default: 3},
    par13: {type: Number, default: 3},
    hole14: {type: Number, default: 3},
    par14: {type: Number, default: 3},
    hole15: {type: Number, default: 3},
    par15: {type: Number, default: 3},
    hole16: {type: Number, default: 3},
    par16: {type: Number, default: 3},
    hole17: {type: Number, default: 3},
    par17: {type: Number, default: 3},
    hole18: {type: Number, default: 3},
    par18: {type: Number, default: 3},
    total: {type: Number, default: 0}
})

module.exports = mongoose.model('Score', scoreSchema);

